### ISSUE TITLE
Catalina & Big Sur CPU Issues

### ISSUE THREAD

**Issue by miyuanbo** [hamcuks/hackintosh-x442urr#2]
i5-8250U BIOS308 X442URR model
Tested Catalina & Big Sur, Bootup perfect, however CPU watts seems to be restricted to around 8W.
Some high-load programs (ex. Adobe PS) can even cause CPU frequency be lowered to 0.40 GHz.
And fan speed seems to be fixed: no matter how CPU works, fan speed always dont change.

**Comment by hamcuks** [comment]
@miyuanbo hi, thank you for your feedback. I think it's because the power limit of this laptop/notebook. If it's used to run heavy task, and reach the 15W power limit, it will throttle around 8-9W and the clockspeed will run on 1.3-1.5 GHz

For fan speed rpm, it's fixed value from AsusSMC kext. There are no other option for fan speed reading, except if you wanna use fakeSMC and their plugins

**Comment by hamcuks** [comment]
Yes, I've tried change the power limit in BIOS, but no luck. I think it's behavior of macOS. Not just in Catalina/Big Sur, in Mojave facing this problem too. Maybe you have another ideas for this problem?

**Comment by doedoey** [comment]
apakah refi ini bisa di pakai untuk hackintosh catalina mas bro,,soalnya laptopnya sama,,apakah ada yang harms dig anti ?

**Comment by doedoey** [comment]
efi maksudnya

**Comment by hamcuks** [comment]
@doedoey bisa

**Comment by zankkizz** [comment]
Reques Buat yg clover bigsur dong bang laptop saya jga 442 ur

**Comment by zankkizz** [comment]
Apakah efi bigsur ini work di catalina bang dan apakah semua fitur seperti wifi grafik sound work jga di catalina.

**Comment by hamcuks** [comment]
Please, read the Description for OS Version support
